apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-mediawiki
  name: mysql-mediawiki-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi